/**
 * PDF Stationery Merger
 *
 * Uses pdf-lib to underlay a stationery PDF behind a generated data PDF.
 * The stationery's first page becomes the background of every data page.
 *
 * Strategy: copy each data page into the output, then inject the stationery's
 * content stream at the BEGINNING of the page's content (so it renders behind).
 * This avoids white-background conflicts from drawPage overlays.
 */
import { PDFDocument } from 'pdf-lib';

/**
 * Merge generated data PDF bytes onto a stationery background PDF.
 *
 * @param dataPdfBytes   The PDF generated by @react-pdf/renderer (Uint8Array or ArrayBuffer)
 * @param stationeryUrl  Base64 data URL or fetch-able URL of the stationery PDF
 * @returns              Merged PDF as a Uint8Array
 */
export async function mergeStationery(
    dataPdfBytes: ArrayBuffer,
    stationeryUrl: string,
): Promise<Uint8Array> {
    // Load both PDFs
    const stationeryBytes = await fetchAsArrayBuffer(stationeryUrl);
    const stationeryDoc = await PDFDocument.load(stationeryBytes);
    const dataDoc = await PDFDocument.load(dataPdfBytes);

    // Create the output document
    const merged = await PDFDocument.create();

    // For each data page, copy it then draw the stationery UNDER it
    const dataPages = dataDoc.getPages();
    for (let i = 0; i < dataPages.length; i++) {
        // Copy the data page into the merged document
        const [copiedDataPage] = await merged.copyPages(dataDoc, [i]);
        const page = merged.addPage(copiedDataPage);

        // Embed the stationery page as a form XObject
        const [embeddedStationery] = await merged.embedPdf(stationeryDoc, [0]);

        // Get current page size
        const { width, height } = page.getSize();

        // Save graphics state, draw stationery at z-bottom, restore
        // We prepend stationery drawing commands so they render BEHIND existing content
        // by using pdf-lib's drawPage at (0,0) covering the full page
        // Since we add the data page first and then draw stationery,
        // we need to use the underlay technique:

        // Actually a simpler approach: create a fresh page, draw stationery first,
        // then draw the data content on top. The key insight is that @react-pdf
        // does NOT add explicit white background fills to its PDFs — CSS backgrounds
        // are only added when explicitly set. So the data overlay is transparent
        // except where content exists.

        // Remove the page we just added and rebuild it properly
        const pageCount = merged.getPageCount();
        merged.removePage(pageCount - 1);

        // Create a fresh page with the data page's dimensions
        const freshPage = merged.addPage([width, height]);

        // Draw stationery FIRST (background layer)
        freshPage.drawPage(embeddedStationery, {
            x: 0,
            y: 0,
            width,
            height,
        });

        // Embed and draw data content ON TOP
        const [embeddedData] = await merged.embedPdf(dataDoc, [i]);
        freshPage.drawPage(embeddedData, {
            x: 0,
            y: 0,
            width,
            height,
        });
    }

    return merged.save();
}

/**
 * Convert a base64 data URL or remote URL to an ArrayBuffer.
 */
async function fetchAsArrayBuffer(url: string): Promise<ArrayBuffer> {
    if (url.startsWith('data:')) {
        // base64 data URL → ArrayBuffer
        const base64 = url.split(',')[1];
        const binary = atob(base64);
        const bytes = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) {
            bytes[i] = binary.charCodeAt(i);
        }
        return bytes.buffer;
    }
    // Remote URL
    const res = await fetch(url);
    return res.arrayBuffer();
}
