/**
 * PDF Stationery Merger
 *
 * Uses pdf-lib to overlay a generated data PDF onto a stationery background PDF.
 * The stationery is the first page of the uploaded PDF — it becomes the background
 * of every page in the data PDF.
 */
import { PDFDocument } from 'pdf-lib';

/**
 * Merge generated data PDF bytes onto a stationery background PDF.
 *
 * @param dataPdfBytes   The PDF generated by @react-pdf/renderer (Uint8Array or ArrayBuffer)
 * @param stationeryUrl  Base64 data URL or fetch-able URL of the stationery PDF
 * @returns              Merged PDF as a Uint8Array
 */
export async function mergeStationery(
    dataPdfBytes: ArrayBuffer,
    stationeryUrl: string,
): Promise<Uint8Array> {
    // Load both PDFs
    const stationeryBytes = await fetchAsArrayBuffer(stationeryUrl);
    const stationeryDoc = await PDFDocument.load(stationeryBytes);
    const dataDoc = await PDFDocument.load(dataPdfBytes);

    // Get the first page of the stationery as a template
    const stationeryPage = stationeryDoc.getPages()[0];
    const { width: sW, height: sH } = stationeryPage.getSize();

    // Create the output document
    const merged = await PDFDocument.create();

    // For each data page, embed the stationery as background
    const dataPages = dataDoc.getPages();
    for (let i = 0; i < dataPages.length; i++) {
        // Embed the stationery page as a form XObject
        const [embeddedStationery] = await merged.embedPdf(stationeryDoc, [0]);

        // Copy the data page
        const [embeddedData] = await merged.copyPages(dataDoc, [i]);

        // Get the data page size
        const { width: dW, height: dH } = embeddedData.getSize();

        // Create a new page with the larger of the two sizes
        const page = merged.addPage([Math.max(sW, dW), Math.max(sH, dH)]);

        // Draw stationery first (background)
        page.drawPage(embeddedStationery, { x: 0, y: 0, width: sW, height: sH });

        // Draw data page on top (overlay)
        const [overlayRef] = await merged.embedPdf(dataDoc, [i]);
        page.drawPage(overlayRef, { x: 0, y: 0, width: dW, height: dH });
    }

    return merged.save();
}

/**
 * Convert a base64 data URL or remote URL to an ArrayBuffer.
 */
async function fetchAsArrayBuffer(url: string): Promise<ArrayBuffer> {
    if (url.startsWith('data:')) {
        // base64 data URL → ArrayBuffer
        const base64 = url.split(',')[1];
        const binary = atob(base64);
        const bytes = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) {
            bytes[i] = binary.charCodeAt(i);
        }
        return bytes.buffer;
    }
    // Remote URL
    const res = await fetch(url);
    return res.arrayBuffer();
}
